// AUTOGENERATED: DO NOT EDIT
using System;

namespace Framework
{
	[Serializable]
	public enum EScene
	{
		Invalid,
		System,
		Services,
		Audio,
		Splash,
		Preloader,
		Login,
		Home,
		Coins,
		Shop,
		Settings,
		Game,
		Results,
		PopupCollection,
		Back,
		Currency,
		Background,
		MoreGames,
		Cleaner,
		Max,
		CharacterSandboxRoot,
		InputSandboxRoot,
		MovementDebugSandboxRoot,
		SpawnSandboxRoot,
		EnvironmentMeshRoot,
		EnvironmentGroundRoot,
		EnvironmentCollisionRoot,
		EnvironmentSandboxRoot,
	}
}
