using FullInspector;
using System.Collections;
using System.Collections.Generic;
using System.IO;
using UnityEditor;
using UnityEngine;

public class SceneEditor_v3 : BaseScriptableObject
{
    public List<string> SceneTypes;

    const string path = "Assets/Framework/Game/Scripts/Data/SceneTypes.cs";
    const string scenepath = "FrameworkFiles/FrameworkScenes.dat";

    private void Awake()
    {
        RefreshSceneFile();
    }

    //REFRESH THE LIST BY READING THE LINES OF THE TEXT FILE
    [InspectorButton]
    private void RefreshSceneFile()
    {
        SceneTypes = new List<string>(File.ReadAllLines(scenepath));
    }

    /// <summary>
    /// Generates a class that contains the SceneTypes Enum
    /// </summary>
    [InspectorButton]
    private void GenerateSceneEnum()
    {
        //UPDATES TEXT FILE USING THE CURRENT LIST
        if (File.Exists(scenepath) == true)
        {
            using (StreamWriter outfile = new StreamWriter(scenepath))
            {
                for (int i = 0; i < SceneTypes.Count; i++)
                {
                    outfile.WriteLine(SceneTypes[i]);

                }
            }
        }

        // delete old class
        if (File.Exists(path))
        {
            File.Delete(path);
        }

        if (File.Exists(path) == false)
        {
            // do not overwrite
            using (StreamWriter outfile = new StreamWriter(path))
            {
                outfile.WriteLine("// AUTOGENERATED: DO NOT EDIT");
                outfile.WriteLine("using System;");
                outfile.WriteLine(string.Empty);
                outfile.WriteLine("namespace Framework");
                outfile.WriteLine("{");
                outfile.WriteLine("\t[Serializable]");
                outfile.WriteLine("\tpublic enum EScene");
                outfile.WriteLine("\t{");

                for (int i = 0; i < SceneTypes.Count; i++)
                {
                    outfile.WriteLine("\t\t{0},", SceneTypes[i]);
                }

                outfile.WriteLine("\t}");
                outfile.WriteLine("}");
            }
        }

        AssetDatabase.Refresh();

        Debug.LogFormat("SceneEditor::GenerateSceneEnum SceneTypes generated!\n");
    }
}
